In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats

In [ ]:

d = pd.read_excel('/Users/cameronrichardson/Documents/Thesis/Code/02102025titration_master copy.xlsx', sheet_name='EXPORT')

         BATCHID   METHOD  SALINITY       PK1       PK2
0     AUTO_SAL35     AUTO        35  5.875567  9.028328
1     AUTO_SAL35     AUTO        35  5.891443  9.069045
2     AUTO_SAL35     AUTO        35  5.869208  8.995413
3     AUTO_SAL35     AUTO        35  5.935637  8.904524
4     AUTO_SAL28     AUTO        28  5.922074  9.010675
5     AUTO_SAL28     AUTO        28  5.846341  9.091961
6     AUTO_SAL28     AUTO        28  5.844815  9.141217
7     AUTO_SAL28     AUTO        28  5.904435  9.075488
8            NaN     AUTO        21       NaN       NaN
9            NaN     AUTO        21       NaN       NaN
10           NaN     AUTO        21       NaN       NaN
11           NaN     AUTO        21       NaN       NaN
12          BP15      MAN        35  5.852904  8.969851
13          BP15      MAN        35  5.882553  9.027550
14          BP15      MAN        35  5.866445  9.027911
15          BP15      MAN        35  5.869938  9.029064
16          BP16      MAN        35  5.858520  9.006951
17          BP16      MAN        35  5.868616  9.032187
18          BP16      MAN        35  5.860886  9.035228
19          BP16      MAN        35  5.873992  9.053462
20          BP17      MAN        35  5.902134  8.999903
21          BP17      MAN        35  5.880130  9.039529
22          BP17      MAN        35  5.873049  8.987341
23          BP17      MAN        35  5.869796  9.001603
24  MANUAL_SAL28      MAN        28  5.910312  9.101926
25  MANUAL_SAL28      MAN        28  5.918828  9.130033
26  MANUAL_SAL28      MAN        28  5.921434  9.133467
27  MANUAL_SAL28      MAN        28  5.914258  9.116595
28  MANUAL_SAL21      MAN        21  5.959075  9.240412
29  MANUAL_SAL21      MAN        21  5.949490  9.180091
30  MANUAL_SAL21      MAN        21  5.947427  9.200242
31  MANUAL_SAL21      MAN        21  5.959902  9.252903
32           NaN  MAN_3MG        35       NaN       NaN
33           NaN  MAN_3MG        35       NaN       NaN
34           NaN  MAN_3MG        35       NaN       NaN
35           NaN  MAN_3MG        35       NaN       NaN
36           NaN  MAN_5MG        35       NaN       NaN
37           NaN  MAN_5MG        35       NaN       NaN
38           NaN  MAN_5MG        35       NaN       NaN
39           NaN  MAN_5MG        35       NaN       NaN